### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by JDruery** [GoIntegro/hateoas#23]
Given the RAML example, the linked GET examples should be "GET /users/1/links/posts" (not "linked"). When I made that change everything works as described.

I've also noticed that the example bundle defines a resource type ("collection") but then it doesn't actually use it in main api.raml file. This makes me wonder if resource types are still a work in progress. When I attempted to use the "collection" resource type on a resource I keep getting the following error: "The resource type declaration is neither a string nor a map." I might be doing something wrong, but if it's the case that resource types are not yet supported then it would be helpful it could please be noted in the docs (just to save us from spending too much time on trying to make it work before it's ready).

I realize I've been putting in issues without helping out by contributing any pull requests. I don't feel that confident using git just yet (sorry), but hopefully in future I might learn enough to be able to help. Thanks again for a fantastic bundle, very appreciated.

**Comment by skqr** [comment]
Hi @JDruery!

Don't worry, any involvement is contribution :smiley_cat: 

I'm currently not maintaining this package, although the guys at GOintegro are.

However - have you checked out the https://github.com/skqr/hateoas-bundle-example project?

It has at least one api.raml example, and might help you.

On the documentation, you're completely right. You can edit that right on the GitHub page. Just browse to that file and hit the pencil icon to edit it on the spot. When saving, you'll be prompted to create a pull request.

Thanks again!

**Comment by JDruery** [comment]
Thanks, glad to be of help :)  Thanks also for the tips. I've been following the example bundle, especially the test cases and it's very helpful. I'll put in the correction for that typo, didn't realize it's so easy to create a pull request.

**Comment by acmenna** [comment]
https://github.com/GoIntegro/hateoas/pull/24
